name: jobtracker_frontend
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Common dependencies
  cupertino_icons: ^1.0.8

  # Needed to make HTTP requests to backend API
  http: ^1.0.0

  # For loading .env files (e.g., API URL)
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add image assets, uncomment and add files here
  # assets:
  #   - assets/images/

  # To add custom fonts, uncomment and configure here
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
